In [2]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4]])

In [4]:
x

array([[1, 2],
       [3, 4]])

In [5]:
y  =  np.rot90(x, k = 1, axes=(0,1))

In [6]:
y

array([[2, 4],
       [1, 3]])

In [7]:
np.flip(y, axis = 0)

array([[1, 3],
       [2, 4]])

In [8]:
np.rot90(x, k = 0, axes=(0,1))

array([[1, 2],
       [3, 4]])

In [9]:
from enum import Enum
class Move(Enum):
    '''
    Selects where you want to place the taken piece. The rest of the pieces are shifted
    '''
    TOP = 0
    BOTTOM = 2
    LEFT = 3
    RIGHT = 1

In [10]:
a = Move.TOP

In [11]:
a.value + 1

1

In [12]:
Move._value2member_map_[0]

<Move.TOP: 0>

In [13]:
x = np.array([[1,1],[-1,0]])
print(x)

[[ 1  1]
 [-1  0]]


In [14]:
def change(a):
    x = np.zeros(a.shape, dtype= int)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if a[i][j] == 0:
                x[i][j] = 1
            elif a[i][j] == 1:
                x[i][j] = 0
            else:
                x[i][j] = a[i][j]
    
    return x


In [15]:
print(change(x))

[[ 0  0]
 [-1  1]]


In [48]:
x = np.array([[2,2],[3,4],[5,6]])
print(x)

[[2 2]
 [3 4]
 [5 6]]


In [49]:
x[1:, 0]

array([3, 5])

In [50]:
x[0:2]

array([[2, 2],
       [3, 4]])

In [51]:
np.sum(x[:,1] == 2 | x[:,1] == 3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [55]:
np.argwhere(x[0,:] == 2).ravel()[0]

0

In [39]:
np.logical_or(x[:,1] == 2, x[:,1] == 3)

array([ True, False, False])

In [ ]:
np.argwhere()

In [57]:
a = np.array([-1,1,1,1,-1,-1,-1,-1])

In [60]:
k = np.argwhere(a == -1).ravel()

In [63]:
k[k>0]

array([4, 5, 6, 7], dtype=int64)

In [1]:
import numpy as np

In [5]:
x = np.array([[1,0],[2,3]])
print(x)

[[1 0]
 [2 3]]


In [6]:
np.diag(x)

array([1, 3])

In [7]:
np.diag(np.flip(x))

array([3, 1])

In [10]:
np.flip(x, axis=1)

array([[0, 1],
       [3, 2]])