In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]])

In [3]:
x

array([[1, 2],
       [3, 4]])

In [5]:
y  =  np.rot90(x, k = 1, axes=(0,1))

In [6]:
y

array([[2, 4],
       [1, 3]])

In [7]:
np.flip(y, axis = 0)

array([[1, 3],
       [2, 4]])

In [11]:
np.rot90(x, k = 0, axes=(0,1))

array([[1, 2],
       [3, 4]])

In [13]:
from enum import Enum
class Move(Enum):
    '''
    Selects where you want to place the taken piece. The rest of the pieces are shifted
    '''
    TOP = 0
    BOTTOM = 2
    LEFT = 3
    RIGHT = 1

In [14]:
a = Move.TOP

In [16]:
a.value + 1

1

In [22]:
Move._value2member_map_[0]

<Move.TOP: 0>

In [40]:
x = np.array([[1,1],[-1,0]])
print(x)

[[ 1  1]
 [-1  0]]


In [41]:
def change(a):
    x = np.zeros(a.shape, dtype= int)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if a[i][j] == 0:
                x[i][j] = 1
            elif a[i][j] == 1:
                x[i][j] = 0
            else:
                x[i][j] = a[i][j]
    
    return x


In [43]:
print(change(x))

[[ 0  0]
 [-1  1]]
