In [1]:
import random
from game import Game, Move, Player
from QPlayer import QPlayer, Environment, train

import numpy as np

SEED = 123456789
np.random.seed(SEED)
random.seed(SEED)

((0, 0), <Move.BOTTOM: 2>)


In [2]:
class RandomPlayer(Player):
    def __init__(self) -> None:
        super().__init__()

    def make_move(self, game: 'Game') -> tuple[tuple[int, int], Move]:
        from_pos = (random.randint(0, 4), random.randint(0, 4))
        move = random.choice([Move.TOP, Move.BOTTOM, Move.LEFT, Move.RIGHT])
        return from_pos, move

In [3]:
player1 = QPlayer()
player1.agent = train(1)

  0%|          | 0/1 [00:00<?, ?it/s]

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
current player 0
((0, 0), <Move.BOTTOM: 2>)
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]]
current player 1
((3, 0), <Move.RIGHT: 1>)
[[-1 -1 -1 -1  1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]]
current player 0
((4, 1), <Move.BOTTOM: 2>)
[[-1 -1 -1 -1  1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1  0]]
current player 1
((3, 4), <Move.RIGHT: 1>)
[[-1 -1 -1 -1  1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1  0  1]]
current player 0
((0, 1), <Move.RIGHT: 1>)
[[-1 -1 -1 -1  1]
 [-1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1  0  1]]
current player 1
((4, 2), <Move.TOP: 0>)
[[-1 -1 -1 -1  1]
 [-1 -1 -1 -1  1]
 [-1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1  0  1]]
current player 0
((4, 3), <Move.LEFT: 3>)
[[-1 -1 -1 -1  1]
 [-1 -1 -1 -1  1]
 [-1 -1 -1 -1  0]
 [ 0 -1 -

In [4]:
counter = 0

for i in range(100):
    g = Game()
    g.print()

    env = Environment()
    env.game = g
    player1.env = env

    player2 = RandomPlayer()
    winner = g.play(player1, player2)
    if winner == 0: ##winner ==1 in case we are the second player
        counter+= 1
    g.print()

    print(f'-----------------{i}-winner_id: {winner}-----------------')

print(f"Winner: Player {winner}")
print(counter)
print(player1.agent.usefullness)


[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
0
(4, 0) Move.BOTTOM
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(4, 1) Move.LEFT
[[-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
0
(4, 3) Move.TOP
[[-1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(4, 2) Move.LEFT
[[-1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
0
(4, 2) Move.TOP
[[-1 -1 -1 -1  0]
 [ 1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(1, 0) Move.RIGHT
[[-1 -1 -1  0  1]
 [ 1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
0
(0, 3) Move.TOP
[[ 0 -1 -1  0  1]
 [-1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(0, 3) Move.TOP
[[ 1 -1 -1  0  1]
 [ 0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
0
(4, 1) Move.BOTTOM
[[ 1 -1 -

In [5]:
print(len(player1.agent.q_table.keys()))
print(player1.agent.epsilon.counter)

def p(a):
    score = a[1]
    move = a[0][1]
    board = a[0][0]
    #x = np.zeros((5,5), dtype=int)
    #for i in range(len(board)):
    #    x[i // 5][i % 5] = board[i]

    return 0, move, score
    


304
1


In [6]:
a = [x for x in player1.agent.q_table.items()]

In [7]:
counter = 0
for i in range(len(a)):
    x, move, score = p(a[i])
    if score == 0:
        #print(x, move)
        counter += 1

In [8]:
counter / len(a)

0.9736842105263158